(require 'mycustom)
(require 'init-cscope)
(require 'init-highlight-current-line)
(require 'init-highlight-parentheses)
(require 'init-ibuffer)
(require 'init-sr-speedbar)
(require 'init-window)
(require 'init-theme)
(require 'init-auto-complete)
(require 'init-CC-mode)
(require 'init-highlight-symbol)
(require 'init-ido)
(require 'init-org-mode)
(require 'init-w3m)

(provide 'init)